import type { Category, Product } from "@/lib/types";

/** Bundled catalog. Mirrors supabase/seed.sql — this powers DEMO MODE and
 *  serves as the single source of truth for the initial live catalog. */

export const seedCategories: Category[] = [
  {
    id: "cat-ties",
    slug: "ties",
    name: "Ties",
    description:
      "Handsome silk and woven neckties — formal solids, regimental stripes and textured weaves.",
    sortOrder: 1,
  },
  {
    id: "cat-cufflinks",
    slug: "cufflinks",
    name: "Cufflinks",
    description:
      "Precision-cast cufflinks in gold, silver and gunmetal finishes, set with stone and enamel.",
    sortOrder: 2,
  },
  {
    id: "cat-brooches",
    slug: "brooches",
    name: "Brooches",
    description:
      "Statement sherwani brooches and minimal lapel pins for weddings and festive occasions.",
    sortOrder: 3,
  },
  {
    id: "cat-pocket-squares",
    slug: "pocket-squares",
    name: "Pocket Squares",
    description:
      "Hand-rolled silk squares in solids, prints and contrast borders — the quiet flourish.",
    sortOrder: 4,
  },
  {
    id: "cat-buttons",
    slug: "buttons",
    name: "Buttons",
    description:
      "Premium blazer, suit and kurta button sets in brass, horn and mother-of-pearl.",
    sortOrder: 5,
  },
  {
    id: "cat-gift-sets",
    slug: "gift-sets",
    name: "Gift Sets",
    description:
      "Coordinated tie, square and cufflink sets in signature gift boxes — ready to give.",
    sortOrder: 6,
  },
];

const d = (day: number) => new Date(2026, 5, day).toISOString();

export const seedProducts: Product[] = [
  // ───────────────────────── TIES ─────────────────────────
  {
    id: "p-001",
    slug: "midnight-navy-silk-tie",
    name: "Midnight Navy Silk Tie",
    category: "ties",
    price: 189900,
    compareAtPrice: 229900,
    description:
      "The one tie every wardrobe is built around. Our Midnight Navy is woven from mulberry silk twill with a discreet sheen that reads formal in daylight and festive by evening. Cut to a classic 7.5 cm width with a wool-blend interlining for a firm, dimpled knot.",
    details: [
      "100% mulberry silk twill",
      "Width 7.5 cm · Length 148 cm",
      "Wool-blend interlining for knot structure",
      "Hand-finished tipping and slip stitch",
      "Dry clean only",
    ],
    material: "silk",
    color: "navy",
    pattern: "solid",
    tags: ["office", "wedding", "bestseller"],
    images: [
      "/products/midnight-navy-silk-tie.svg",
      "/products/midnight-navy-silk-tie-detail.svg",
    ],
    stock: 42,
    featured: true,
    active: true,
    createdAt: d(1),
  },
  {
    id: "p-002",
    slug: "charcoal-herringbone-tie",
    name: "Charcoal Herringbone Tie",
    category: "ties",
    price: 179900,
    compareAtPrice: null,
    description:
      "A study in quiet texture. The herringbone weave catches light along its chevrons, giving a plain-looking tie unusual depth up close — the detail people notice in a boardroom without knowing why.",
    details: [
      "Silk-wool blend, herringbone weave",
      "Width 7.5 cm · Length 148 cm",
      "Muted matte finish",
      "Hand-finished tipping",
      "Dry clean only",
    ],
    material: "silk-wool",
    color: "charcoal",
    pattern: "textured",
    tags: ["office", "interview"],
    images: [
      "/products/charcoal-herringbone-tie.svg",
      "/products/charcoal-herringbone-tie-detail.svg",
    ],
    stock: 35,
    featured: false,
    active: true,
    createdAt: d(2),
  },
  {
    id: "p-003",
    slug: "burgundy-repp-stripe-tie",
    name: "Burgundy Repp Stripe Tie",
    category: "ties",
    price: 199900,
    compareAtPrice: null,
    description:
      "Our take on the classic English regimental: deep burgundy grounds crossed with fine gold stripes on a ribbed repp weave. Sharp with navy, grey and charcoal tailoring alike.",
    details: [
      "100% silk, repp (ribbed) weave",
      "Width 7.5 cm · Length 148 cm",
      "Diagonal stripe, London direction",
      "Hand-finished tipping and bar tack",
      "Dry clean only",
    ],
    material: "silk",
    color: "burgundy",
    pattern: "striped",
    tags: ["office", "festive", "bestseller"],
    images: [
      "/products/burgundy-repp-stripe-tie.svg",
      "/products/burgundy-repp-stripe-tie-detail.svg",
    ],
    stock: 38,
    featured: true,
    active: true,
    createdAt: d(3),
  },
  {
    id: "p-004",
    slug: "regimental-navy-gold-stripe-tie",
    name: "Regimental Navy & Gold Stripe Tie",
    category: "ties",
    price: 189900,
    compareAtPrice: null,
    description:
      "Bold, even stripes of midnight navy and antique gold — a club tie with presence. Wear it when the room should remember you.",
    details: [
      "100% silk, repp weave",
      "Width 8 cm · Length 148 cm",
      "Balanced block stripe",
      "Wool-blend interlining",
      "Dry clean only",
    ],
    material: "silk",
    color: "navy",
    pattern: "striped",
    tags: ["office", "convocation"],
    images: [
      "/products/regimental-navy-gold-stripe-tie.svg",
      "/products/regimental-navy-gold-stripe-tie-detail.svg",
    ],
    stock: 30,
    featured: false,
    active: true,
    createdAt: d(4),
  },
  {
    id: "p-005",
    slug: "ivory-wedding-jacquard-tie",
    name: "Ivory Wedding Jacquard Tie",
    category: "ties",
    price: 249900,
    compareAtPrice: 279900,
    description:
      "Woven for wedding mornings: an ivory jacquard with a tonal diamond motif that photographs beautifully against bandhgalas and dark suits. Subtle enough for the groom's party, special enough for the groom.",
    details: [
      "Silk jacquard, tonal diamond motif",
      "Width 7.5 cm · Length 148 cm",
      "Pairs with our ivory pocket square",
      "Presented in a signature gift sleeve",
      "Dry clean only",
    ],
    material: "silk",
    color: "ivory",
    pattern: "textured",
    tags: ["wedding", "gift"],
    images: [
      "/products/ivory-wedding-jacquard-tie.svg",
      "/products/ivory-wedding-jacquard-tie-detail.svg",
    ],
    stock: 24,
    featured: true,
    active: true,
    createdAt: d(5),
  },
  {
    id: "p-006",
    slug: "forest-green-grenadine-tie",
    name: "Forest Green Grenadine Tie",
    category: "ties",
    price: 219900,
    compareAtPrice: null,
    description:
      "Grenadine's open, airy weave is the connoisseur's choice — matte, grippy and quietly luxurious. Deep forest green that flatters tan, olive and grey.",
    details: [
      "100% silk, garza fina grenadine weave",
      "Width 7.5 cm · Length 148 cm",
      "Untipped, hand-rolled edges",
      "Knots with a natural, relaxed dimple",
      "Dry clean only",
    ],
    material: "silk",
    color: "green",
    pattern: "textured",
    tags: ["office", "evening"],
    images: [
      "/products/forest-green-grenadine-tie.svg",
      "/products/forest-green-grenadine-tie-detail.svg",
    ],
    stock: 22,
    featured: false,
    active: true,
    createdAt: d(6),
  },
  {
    id: "p-007",
    slug: "steel-grey-pin-dot-tie",
    name: "Steel Grey Pin-Dot Tie",
    category: "ties",
    price: 169900,
    compareAtPrice: null,
    description:
      "Fine ivory pin-dots on a steel grey ground — the pattern that behaves like a solid but works harder. The safest brave choice in the drawer.",
    details: [
      "100% silk twill, printed pin-dot",
      "Width 7.5 cm · Length 148 cm",
      "Wool-blend interlining",
      "Hand-finished tipping",
      "Dry clean only",
    ],
    material: "silk",
    color: "grey",
    pattern: "printed",
    tags: ["office", "interview"],
    images: [
      "/products/steel-grey-pin-dot-tie.svg",
      "/products/steel-grey-pin-dot-tie-detail.svg",
    ],
    stock: 40,
    featured: false,
    active: true,
    createdAt: d(7),
  },
  {
    id: "p-008",
    slug: "black-satin-formal-tie",
    name: "Black Satin Formal Tie",
    category: "ties",
    price: 159900,
    compareAtPrice: null,
    description:
      "For tuxedos, black-tie optional and evenings that call for polish. A liquid satin black with just enough body to knot cleanly every time.",
    details: [
      "Silk satin, high-lustre finish",
      "Width 7 cm · Length 148 cm",
      "Slim-classic profile",
      "Hand-finished tipping",
      "Dry clean only",
    ],
    material: "silk",
    color: "black",
    pattern: "solid",
    tags: ["evening", "formal"],
    images: [
      "/products/black-satin-formal-tie.svg",
      "/products/black-satin-formal-tie-detail.svg",
    ],
    stock: 33,
    featured: false,
    active: true,
    createdAt: d(8),
  },

  // ─────────────────────── CUFFLINKS ───────────────────────
  {
    id: "p-009",
    slug: "gold-tone-knot-cufflinks",
    name: "Gold-Tone Knot Cufflinks",
    category: "cufflinks",
    price: 149900,
    compareAtPrice: 179900,
    description:
      "A sculpted knot in polished gold tone — the cufflink equivalent of a firm handshake. Solid brass with a whale-back closure that fastens in one motion.",
    details: [
      "Premium brass, 18k gold-tone plating",
      "Knot face 16 mm",
      "Whale-back closure",
      "Anti-tarnish e-coating",
      "Signature gift box included",
    ],
    material: "brass",
    color: "gold",
    pattern: "solid",
    tags: ["office", "wedding", "gift", "bestseller"],
    images: [
      "/products/gold-tone-knot-cufflinks.svg",
      "/products/gold-tone-knot-cufflinks-detail.svg",
    ],
    stock: 50,
    featured: true,
    active: true,
    createdAt: d(9),
  },
  {
    id: "p-010",
    slug: "onyx-square-cufflinks",
    name: "Onyx Square Cufflinks",
    category: "cufflinks",
    price: 189900,
    compareAtPrice: null,
    description:
      "A slab of jet-black onyx framed in rhodium-plated steel. Severe, architectural and unfailingly formal — made for French cuffs and final interviews.",
    details: [
      "Natural black onyx inlay",
      "Rhodium-plated stainless steel frame",
      "Face 15 × 15 mm",
      "Whale-back closure",
      "Signature gift box included",
    ],
    material: "steel",
    color: "black",
    pattern: "solid",
    tags: ["office", "evening", "gift"],
    images: [
      "/products/onyx-square-cufflinks.svg",
      "/products/onyx-square-cufflinks-detail.svg",
    ],
    stock: 28,
    featured: false,
    active: true,
    createdAt: d(10),
  },
  {
    id: "p-011",
    slug: "mother-of-pearl-round-cufflinks",
    name: "Mother-of-Pearl Round Cufflinks",
    category: "cufflinks",
    price: 229900,
    compareAtPrice: null,
    description:
      "Iridescent mother-of-pearl discs that shift from silver to blush as the light moves. Set in gold-tone bezels — heirloom material, modern geometry.",
    details: [
      "Natural mother-of-pearl face",
      "Brass bezel, gold-tone plating",
      "Face 16 mm diameter",
      "Whale-back closure",
      "Signature gift box included",
    ],
    material: "mother-of-pearl",
    color: "ivory",
    pattern: "solid",
    tags: ["wedding", "gift"],
    images: [
      "/products/mother-of-pearl-round-cufflinks.svg",
      "/products/mother-of-pearl-round-cufflinks-detail.svg",
    ],
    stock: 20,
    featured: true,
    active: true,
    createdAt: d(11),
  },
  {
    id: "p-012",
    slug: "gunmetal-hexagon-cufflinks",
    name: "Gunmetal Hexagon Cufflinks",
    category: "cufflinks",
    price: 139900,
    compareAtPrice: null,
    description:
      "Brushed gunmetal hexagons with a machined edge — engineering-room aesthetics for the modern office. Pairs especially well with grey and blue shirting.",
    details: [
      "Stainless steel, brushed gunmetal finish",
      "Face 16 mm across flats",
      "Whale-back closure",
      "Scratch-resistant coating",
      "Signature gift box included",
    ],
    material: "steel",
    color: "grey",
    pattern: "solid",
    tags: ["office"],
    images: [
      "/products/gunmetal-hexagon-cufflinks.svg",
      "/products/gunmetal-hexagon-cufflinks-detail.svg",
    ],
    stock: 45,
    featured: false,
    active: true,
    createdAt: d(12),
  },
  {
    id: "p-013",
    slug: "royal-blue-enamel-cufflinks",
    name: "Royal Blue Enamel Cufflinks",
    category: "cufflinks",
    price: 159900,
    compareAtPrice: null,
    description:
      "Deep royal blue enamel poured into a polished silver-tone ring — a controlled shot of colour at the cuff that lifts an otherwise sober suit.",
    details: [
      "Hand-filled vitreous enamel",
      "Brass base, silver-tone plating",
      "Face 15 mm diameter",
      "Whale-back closure",
      "Signature gift box included",
    ],
    material: "brass",
    color: "blue",
    pattern: "solid",
    tags: ["office", "festive", "gift"],
    images: [
      "/products/royal-blue-enamel-cufflinks.svg",
      "/products/royal-blue-enamel-cufflinks-detail.svg",
    ],
    stock: 32,
    featured: false,
    active: true,
    createdAt: d(13),
  },
  {
    id: "p-014",
    slug: "silver-bar-cufflinks",
    name: "Silver Bar Cufflinks",
    category: "cufflinks",
    price: 129900,
    compareAtPrice: null,
    description:
      "A clean, mirror-polished bar. No stone, no motif, no noise — the minimalist's cufflink, engraved-ready for initials.",
    details: [
      "Stainless steel, mirror polish",
      "Bar 20 × 6 mm",
      "Whale-back closure",
      "Suitable for engraving",
      "Signature gift box included",
    ],
    material: "steel",
    color: "silver",
    pattern: "solid",
    tags: ["office", "minimal", "gift"],
    images: [
      "/products/silver-bar-cufflinks.svg",
      "/products/silver-bar-cufflinks-detail.svg",
    ],
    stock: 55,
    featured: false,
    active: true,
    createdAt: d(14),
  },

  // ─────────────────────── BROOCHES ────────────────────────
  {
    id: "p-015",
    slug: "pearl-drop-sherwani-brooch",
    name: "Pearl Drop Sherwani Brooch",
    category: "brooches",
    price: 199900,
    compareAtPrice: 239900,
    description:
      "The wedding-day essential: a gold-tone crest set with crystals, finishing in a single suspended pearl that moves as you do. Designed to sit on sherwanis, bandhgalas and achkans without pulling the drape.",
    details: [
      "Brass base, 18k gold-tone plating",
      "Shell pearl drop, crystal pavé",
      "Length 65 mm including drop",
      "Secure locking pin with safety catch",
      "Signature gift box included",
    ],
    material: "brass",
    color: "gold",
    pattern: "solid",
    tags: ["wedding", "festive", "bestseller"],
    images: [
      "/products/pearl-drop-sherwani-brooch.svg",
      "/products/pearl-drop-sherwani-brooch-detail.svg",
    ],
    stock: 26,
    featured: true,
    active: true,
    createdAt: d(15),
  },
  {
    id: "p-016",
    slug: "kundan-peacock-brooch",
    name: "Kundan Peacock Brooch",
    category: "brooches",
    price: 249900,
    compareAtPrice: null,
    description:
      "A peacock rendered in kundan-style set stones with an emerald-green enamel tail — heritage craft vocabulary in a piece sized for the modern lapel.",
    details: [
      "Kundan-style stone setting",
      "Green and gold enamel work",
      "Height 55 mm",
      "Secure locking pin",
      "Signature gift box included",
    ],
    material: "brass",
    color: "green",
    pattern: "printed",
    tags: ["wedding", "festive"],
    images: [
      "/products/kundan-peacock-brooch.svg",
      "/products/kundan-peacock-brooch-detail.svg",
    ],
    stock: 18,
    featured: false,
    active: true,
    createdAt: d(16),
  },
  {
    id: "p-017",
    slug: "minimal-gold-leaf-lapel-pin",
    name: "Minimal Gold Leaf Lapel Pin",
    category: "brooches",
    price: 99900,
    compareAtPrice: null,
    description:
      "A single laurel leaf in brushed gold tone. The quietest thing on this site — and the one that gets asked about most.",
    details: [
      "Brass, brushed gold-tone finish",
      "Height 40 mm",
      "Stick pin with clutch back",
      "Wear on lapel or collar",
      "Signature gift pouch included",
    ],
    material: "brass",
    color: "gold",
    pattern: "solid",
    tags: ["office", "minimal", "gift"],
    images: [
      "/products/minimal-gold-leaf-lapel-pin.svg",
      "/products/minimal-gold-leaf-lapel-pin-detail.svg",
    ],
    stock: 60,
    featured: false,
    active: true,
    createdAt: d(17),
  },
  {
    id: "p-018",
    slug: "crystal-starburst-brooch",
    name: "Crystal Starburst Brooch",
    category: "brooches",
    price: 179900,
    compareAtPrice: null,
    description:
      "Rays of channel-set crystals bursting from a central stone — reception-night sparkle that stays on the right side of flamboyant.",
    details: [
      "Clear crystal pavé, silver-tone base",
      "Diameter 48 mm",
      "Secure locking pin with safety catch",
      "Best on dark sherwanis and tuxedos",
      "Signature gift box included",
    ],
    material: "brass",
    color: "silver",
    pattern: "solid",
    tags: ["wedding", "evening"],
    images: [
      "/products/crystal-starburst-brooch.svg",
      "/products/crystal-starburst-brooch-detail.svg",
    ],
    stock: 22,
    featured: false,
    active: true,
    createdAt: d(18),
  },
  {
    id: "p-019",
    slug: "ruby-red-stone-brooch",
    name: "Ruby-Red Stone Brooch",
    category: "brooches",
    price: 219900,
    compareAtPrice: null,
    description:
      "A deep ruby-red centre stone in a gold-tone floral mount. Made for maroon-and-gold wedding palettes and festive bandhgalas.",
    details: [
      "Ruby-red glass centre stone",
      "Brass mount, gold-tone plating",
      "Diameter 45 mm",
      "Secure locking pin",
      "Signature gift box included",
    ],
    material: "brass",
    color: "burgundy",
    pattern: "solid",
    tags: ["wedding", "festive"],
    images: [
      "/products/ruby-red-stone-brooch.svg",
      "/products/ruby-red-stone-brooch-detail.svg",
    ],
    stock: 20,
    featured: false,
    active: true,
    createdAt: d(19),
  },

  // ───────────────────── POCKET SQUARES ─────────────────────
  {
    id: "p-020",
    slug: "ivory-silk-pocket-square",
    name: "Ivory Silk Pocket Square",
    category: "pocket-squares",
    price: 89900,
    compareAtPrice: null,
    description:
      "The white-square rule, upgraded: a warm ivory silk with hand-rolled edges that sits with more ease than crisp cotton. The single most versatile accessory we make.",
    details: [
      "100% silk twill",
      "40 × 40 cm",
      "Hand-rolled and hand-stitched edges",
      "Warm ivory, pairs with everything",
      "Dry clean recommended",
    ],
    material: "silk",
    color: "ivory",
    pattern: "solid",
    tags: ["wedding", "office", "bestseller"],
    images: [
      "/products/ivory-silk-pocket-square.svg",
      "/products/ivory-silk-pocket-square-detail.svg",
    ],
    stock: 48,
    featured: true,
    active: true,
    createdAt: d(20),
  },
  {
    id: "p-021",
    slug: "burgundy-paisley-pocket-square",
    name: "Burgundy Paisley Pocket Square",
    category: "pocket-squares",
    price: 99900,
    compareAtPrice: null,
    description:
      "A dense paisley print in burgundy, gold and ink — fold it flat for restraint or puff it for flourish. Built to be the interesting corner of a sober outfit.",
    details: [
      "Silk twill, screen-printed paisley",
      "40 × 40 cm",
      "Hand-rolled edges",
      "Burgundy ground with gold motif",
      "Dry clean recommended",
    ],
    material: "silk",
    color: "burgundy",
    pattern: "printed",
    tags: ["festive", "evening"],
    images: [
      "/products/burgundy-paisley-pocket-square.svg",
      "/products/burgundy-paisley-pocket-square-detail.svg",
    ],
    stock: 36,
    featured: false,
    active: true,
    createdAt: d(21),
  },
  {
    id: "p-022",
    slug: "navy-polka-pocket-square",
    name: "Navy Polka Pocket Square",
    category: "pocket-squares",
    price: 84900,
    compareAtPrice: null,
    description:
      "Ivory dots on a navy ground — the pocket square that agrees with every tie you own. A one-corner-up fold shows the dots best.",
    details: [
      "Silk twill, printed polka dot",
      "40 × 40 cm",
      "Hand-rolled edges",
      "Ivory dot on navy",
      "Dry clean recommended",
    ],
    material: "silk",
    color: "navy",
    pattern: "printed",
    tags: ["office"],
    images: [
      "/products/navy-polka-pocket-square.svg",
      "/products/navy-polka-pocket-square-detail.svg",
    ],
    stock: 40,
    featured: false,
    active: true,
    createdAt: d(22),
  },
  {
    id: "p-023",
    slug: "gold-contrast-border-pocket-square",
    name: "Gold Contrast-Border Pocket Square",
    category: "pocket-squares",
    price: 94900,
    compareAtPrice: null,
    description:
      "Charcoal centre, antique-gold border. Folded flat it shows a clean gold line above the pocket — a draughtsman's accent for dark suits.",
    details: [
      "Silk twill, woven contrast border",
      "40 × 40 cm",
      "Hand-rolled edges",
      "Charcoal with antique gold frame",
      "Dry clean recommended",
    ],
    material: "silk",
    color: "charcoal",
    pattern: "solid",
    tags: ["office", "evening"],
    images: [
      "/products/gold-contrast-border-pocket-square.svg",
      "/products/gold-contrast-border-pocket-square-detail.svg",
    ],
    stock: 30,
    featured: false,
    active: true,
    createdAt: d(23),
  },
  {
    id: "p-024",
    slug: "emerald-printed-pocket-square",
    name: "Emerald Printed Pocket Square",
    category: "pocket-squares",
    price: 99900,
    compareAtPrice: null,
    description:
      "A botanical medallion print in emerald and ivory. The colour that makes grey flannel and camel jackets suddenly look considered.",
    details: [
      "Silk twill, medallion print",
      "40 × 40 cm",
      "Hand-rolled edges",
      "Emerald ground, ivory motif",
      "Dry clean recommended",
    ],
    material: "silk",
    color: "green",
    pattern: "printed",
    tags: ["festive", "evening"],
    images: [
      "/products/emerald-printed-pocket-square.svg",
      "/products/emerald-printed-pocket-square-detail.svg",
    ],
    stock: 28,
    featured: false,
    active: true,
    createdAt: d(24),
  },

  // ─────────────────────── BUTTONS ─────────────────────────
  {
    id: "p-025",
    slug: "golden-brass-blazer-buttons",
    name: "Golden Brass Blazer Buttons (Set of 8)",
    category: "buttons",
    price: 129900,
    compareAtPrice: null,
    description:
      "Re-button a blazer and it becomes a different garment. Eight solid brass buttons — two front, six cuff — with a laurel crest and antique gold finish.",
    details: [
      "Solid brass, antique gold finish",
      "2 × 20 mm front, 6 × 15 mm cuff",
      "Laurel crest engraving",
      "Shank back for easy tailoring",
      "Presented in a signature case",
    ],
    material: "brass",
    color: "gold",
    pattern: "solid",
    tags: ["office", "gift"],
    images: [
      "/products/golden-brass-blazer-buttons.svg",
      "/products/golden-brass-blazer-buttons-detail.svg",
    ],
    stock: 34,
    featured: false,
    active: true,
    createdAt: d(25),
  },
  {
    id: "p-026",
    slug: "antique-silver-kurta-buttons",
    name: "Antique Silver Kurta Buttons (Set of 5)",
    category: "buttons",
    price: 119900,
    compareAtPrice: 139900,
    description:
      "Five chained kurta buttons in an antique silver finish with hand-cut filigree detail — festive tradition, engineered to swap between kurtas in seconds.",
    details: [
      "Brass, antique silver plating",
      "Filigree engraving",
      "12 mm faces, linked chain",
      "Fits standard kurta buttonholes",
      "Presented in a signature case",
    ],
    material: "brass",
    color: "silver",
    pattern: "textured",
    tags: ["festive", "wedding", "bestseller"],
    images: [
      "/products/antique-silver-kurta-buttons.svg",
      "/products/antique-silver-kurta-buttons-detail.svg",
    ],
    stock: 44,
    featured: true,
    active: true,
    createdAt: d(26),
  },
  {
    id: "p-027",
    slug: "mother-of-pearl-shirt-buttons",
    name: "Mother-of-Pearl Shirt Buttons (Set of 10)",
    category: "buttons",
    price: 89900,
    compareAtPrice: null,
    description:
      "Ten genuine mother-of-pearl buttons to elevate a favourite shirt — the upgrade tailors quietly recommend. Natural iridescence no plastic can imitate.",
    details: [
      "Genuine river-shell mother-of-pearl",
      "10 × 11.5 mm, 4-hole",
      "3 mm thickness — satisfying heft",
      "Fits standard shirt plackets",
      "Presented in a signature pouch",
    ],
    material: "mother-of-pearl",
    color: "ivory",
    pattern: "solid",
    tags: ["office", "minimal"],
    images: [
      "/products/mother-of-pearl-shirt-buttons.svg",
      "/products/mother-of-pearl-shirt-buttons-detail.svg",
    ],
    stock: 52,
    featured: false,
    active: true,
    createdAt: d(27),
  },
  {
    id: "p-028",
    slug: "black-horn-suit-buttons",
    name: "Black Horn Suit Buttons (Set of 6)",
    category: "buttons",
    price: 99900,
    compareAtPrice: null,
    description:
      "Six genuine horn buttons in deep espresso-black with natural grain variation — the finishing detail on bespoke suits, available for yours.",
    details: [
      "Genuine buffalo horn, polished",
      "2 × 20 mm front, 4 × 15 mm cuff",
      "Natural grain — each set unique",
      "4-hole, tailor-ready",
      "Presented in a signature case",
    ],
    material: "horn",
    color: "black",
    pattern: "solid",
    tags: ["office", "minimal"],
    images: [
      "/products/black-horn-suit-buttons.svg",
      "/products/black-horn-suit-buttons-detail.svg",
    ],
    stock: 38,
    featured: false,
    active: true,
    createdAt: d(28),
  },

  // ────────────────────── GIFT SETS ────────────────────────
  {
    id: "p-029",
    slug: "the-monarch-gift-set",
    name: "The Monarch Gift Set",
    category: "gift-sets",
    price: 449900,
    compareAtPrice: 519900,
    description:
      "Our signature trio: the Midnight Navy Silk Tie, Ivory Silk Pocket Square and Gold-Tone Knot Cufflinks, coordinated and boxed. The default answer to 'what do I gift him?'",
    details: [
      "Midnight Navy Silk Tie (silk twill)",
      "Ivory Silk Pocket Square (hand-rolled)",
      "Gold-Tone Knot Cufflinks (brass)",
      "Signature rigid gift box with sleeve",
      "Complimentary gift note at checkout",
    ],
    material: "silk",
    color: "navy",
    pattern: "solid",
    tags: ["gift", "wedding", "office", "bestseller"],
    images: [
      "/products/the-monarch-gift-set.svg",
      "/products/the-monarch-gift-set-detail.svg",
    ],
    stock: 25,
    featured: true,
    active: true,
    createdAt: d(29),
  },
  {
    id: "p-030",
    slug: "the-heir-wedding-set",
    name: "The Heir Wedding Set",
    category: "gift-sets",
    price: 499900,
    compareAtPrice: null,
    description:
      "Built for the wedding season: the Pearl Drop Sherwani Brooch, Antique Silver Kurta Buttons and Ivory Silk Pocket Square in one ceremony-ready box.",
    details: [
      "Pearl Drop Sherwani Brooch",
      "Antique Silver Kurta Buttons (set of 5)",
      "Ivory Silk Pocket Square",
      "Signature rigid gift box with sleeve",
      "Complimentary gift note at checkout",
    ],
    material: "brass",
    color: "gold",
    pattern: "solid",
    tags: ["gift", "wedding", "festive"],
    images: [
      "/products/the-heir-wedding-set.svg",
      "/products/the-heir-wedding-set-detail.svg",
    ],
    stock: 18,
    featured: true,
    active: true,
    createdAt: d(30),
  },
  {
    id: "p-031",
    slug: "the-boardroom-set",
    name: "The Boardroom Set",
    category: "gift-sets",
    price: 349900,
    compareAtPrice: null,
    description:
      "Promotion-day armour: the Charcoal Herringbone Tie and Gunmetal Hexagon Cufflinks, matched and boxed for the corner-office trajectory.",
    details: [
      "Charcoal Herringbone Tie (silk-wool)",
      "Gunmetal Hexagon Cufflinks (steel)",
      "Signature rigid gift box with sleeve",
      "Complimentary gift note at checkout",
    ],
    material: "silk-wool",
    color: "charcoal",
    pattern: "textured",
    tags: ["gift", "office"],
    images: [
      "/products/the-boardroom-set.svg",
      "/products/the-boardroom-set-detail.svg",
    ],
    stock: 22,
    featured: false,
    active: true,
    createdAt: d(31),
  },
];
